### ISSUE TITLE
Haunt Spell Broken

### ISSUE THREAD

**Issue by Zbucket** [Zydrax/ShingraWoW#13]
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

**Description:**

After killing dozens of mobs with haunt, the spell didn't reset it's cooldown.

**Current behaviour:**

After killing dozens of mobs with haunt, the spell didn't reset it's cooldown.

**Expected behaviour:**

It should reset Cooldown

[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes containing C++, create a Pull Request.)

**Comment by Zydrax** [comment]
Fixed by : whoami  , Thenk you for your support  :)
